server.port=8080
spring.application.name=jobboard

# H2 Database Configuration
# spring.datasource.url=jdbc:h2:mem:jobboard
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
# spring.h2.console.settings.web-allow-others=true
# spring.datasource.driverClassName=org.h2.Driver

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/jobboard
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true
info.app.name=Job Board
info.app.description=Job Board Application
info.app.version=1.0.0
info.app.java.version=17

docker run -d --name pgadmin -e PGADMIN_DEFAULT_EMAIL=admin@example.com -e PGADMIN_DEFAULT_PASSWORD=admin  -p 80:80 dpage/pgadmin4